### ISSUE TITLE
Invalid Discord Link

### ISSUE THREAD

**Issue by Joseph-M-Cook** [showlab/computer_use_ootb#26]
The Discord invitation link in the README is outdated and/or invalid. It would be great to connect with other devs!

Thank you.

**Comment by DanielKehoe** [comment]
![Discord-invalid](https://github.com/user-attachments/assets/1c356eb4-1fc0-4c46-8e4f-7fa258dd9d6e)

**Comment by DanielKehoe** [comment]
I noticed (from the folder`.zed`) that the team is using Zed? Do you have a channel in Zed for developer discussion? Could we join with a Zed channel link?

**Comment by h-siyuan** [comment]
We don't use Zed frequently now, but we'll try again to see if it boosts our productivity:)

**Comment by Joseph-M-Cook** [comment]
Awesome, just tested the link on the README and it works. Thank you!
