### ISSUE TITLE
Correct custom_system_prompt for Mac

### ISSUE THREAD

**Issue by DanielKehoe** [showlab/computer_use_ootb#32]
I'm using a 15-inch MacBook Air (M3).

The GUI agent told me "at the start of our conversation, there was a specific note stating "NOTE: you are operating a Linux machine".

That's because of this code in `app.py > def setup_state`:
```
device_os_name = "Windows" if platform.platform == "Windows" else "Mac" if platform.platform == "Darwin" else "Linux"
```

It should be:
```
device_os_name = "Windows" if platform.system() == "Windows" else "Mac" if platform.system() == "Darwin" else "Linux"
```
With this change, the GUI agent gets it right, with "NOTE: you are operating a Mac machine".

A good way to check is to ask the GUI agent to show the window "About This Mac". It didn't work until I changed the code.

**Comment by h-siyuan** [comment]
Thank you for your suggestion! This bug is now fixed. More suggestions are welcomed:)
