### ISSUE TITLE
Quick Start Prompt of Honkai Star Rail Not Working

### ISSUE THREAD

**Issue by Opdoop** [showlab/computer_use_ootb#37]
In Windows 10, the computer control is not working at all. The bot message says to press escape, but the game does not change.
I pulled this project and used a new conda environment with the required packages. 
![1860878766155468800](https://github.com/user-attachments/assets/85ccb47d-8305-4256-bebc-db8ac5893ac7)

**Comment by Opdoop** [comment]
It works! Thanks!

**Comment by ZHANGJINKUI** [comment]
> It works! Thanks!

Hello, may I ask if the models you’re using are all official models? Are they capable of automating operations in Star Rail? Would you be willing to share your configuration and setup details?
