### ISSUE TITLE
Getting error code 400 on Windows

### ISSUE THREAD

**Issue by yvrjsharma** [showlab/computer_use_ootb#4]
Great work on the release! However, I am unable to run the app on my Windows 11 machine. Getting this error:
```
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.2.content.0.tool_result.content.0.image.source.base64: image exceeds 5 MB maximum: 5480308 bytes > 5242880 bytes'}} 
```
Full error log:
[error_log.txt](https://github.com/user-attachments/files/17510317/error_log.txt)

**Comment by h-siyuan** [comment]
Hi, now we have added support for any resolution & resolution scale and multiple displays, you can try the latest version:)

**Comment by yvrjsharma** [comment]
Awesome, thanks for the update!
