### ISSUE TITLE
[Apple M2 mps with 16G RAM]run app.py and got error :AttributeError: dlsym(0x3e48556bc, objc_msgSendSuper_stret): symbol not found

### ISSUE THREAD

**Issue by Zhangronger** [showlab/computer_use_ootb#49]
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/e2992a62-2aeb-4519-bfdf-7ccaa835a76e">
I got error when a followed the steps specified in README. But I still got error.
Python : 3.11
OS: Mac os 14.4
<img width="199" alt="image" src="https://github.com/user-attachments/assets/e5fd9ca9-588d-4551-81d2-3c8e69ed01c6">

**Comment by h-siyuan** [comment]
Please check the mode of the terminal where the app is running, i.e., whether the terminal is running in Rosseta mode.
